WebSite.EndPoint/Models/ViewComponents/BasketComponent.cs
using Application.BasketsService;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebSite.EndPoint.Utilities;

namespace WebSite.EndPoint.Models.ViewComponents
{
    public class BasketComponent : ViewComponent
    {
        private readonly IBasketService basketService;
        public BasketComponent(IBasketService basketService)
        {
            this.basketService = basketService;
        }
        private ClaimsPrincipal userClaimsPrincipal => ViewContext?.HttpContext?.User;
        public IViewComponentResult Invoke()
        {
            BasketDto basket = null;
            if (User.Identity.IsAuthenticated)
            {
                basket = basketService.GetBasketForUser(ClaimUtility.GetUserId(userClaimsPrincipal));
            }
            else
            {
                string basketCookieName = "BasketId";
                if (Request.Cookies.ContainsKey(basketCookieName))
                {
                    var buyerId = Request.Cookies[basketCookieName];
                    basket = basketService.GetBasketForUser(buyerId);
                }

            }
            return View(viewName: "BasketComponent", model: basket);
        }
    }
}

WebSite.EndPoint/Controllers/BasketController.cs
using Application.BasketsService;
using Application.Discounts;
using Application.Orders;
using Application.Payments;
using Application.Users;
using Domain.Order;
using Domain.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using WebSite.EndPoint.Models.ViewModels.Baskets;
using WebSite.EndPoint.Utilities;

namespace WebSite.EndPoint.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IBasketService basketService;
        private readonly SignInManager<User> signInManager;
        private readonly IUserAddressService userAddressService;
        private readonly IOrderService orderService;
        private readonly IPaymentService paymentService;
        private readonly IDiscountService discountService;
        private readonly UserManager<User> userManager;
        private string userId = null;

        public BasketController(IBasketService basketService 
            , SignInManager<User> signInManager , 
            IUserAddressService userAddressService,
            IOrderService orderService,
            IPaymentService paymentService
            ,IDiscountService discountService
            ,UserManager<User> userManager)
        {
            this.basketService = basketService;
            this.signInManager = signInManager;
            this.userAddressService = userAddressService;
            this.orderService = orderService;
            this.paymentService = paymentService;
            this.discountService = discountService;
            this.userManager = userManager;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var data = GetOrSetBasket();
            return View(data);
        }


        [AllowAnonymous]
        [HttpPost]
        public IActionResult Index(int CatalogitemId , int quantity=1)
        {
            var basket = GetOrSetBasket();
            basketService.AddItemToBasket(basket.Id, CatalogitemId, quantity);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult RemoveItemFromBasket(int ItemId)
        {
            basketService.RemoveItemFromBasket(ItemId);
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult setQuantity(int basketItemId, int quantity)
        {
            return Json(basketService.SetQuantities(basketItemId, quantity));
        }

        public IActionResult ShippingPayment()
        {
            ShippingPaymentViewModel model = new ShippingPaymentViewModel();
            string userId = ClaimUtility.GetUserId(User);
            model.Basket = basketService.GetBasketForUser(userId);
            model.UserAddresses = userAddressService.GetAddress(userId);
            return View(model);
        }

        [HttpPost]
        public IActionResult ShippingPayment(int Address, PaymentMethod PaymentMethod)
        {
            string userId = ClaimUtility.GetUserId(User);
            var basket = basketService.GetBasketForUser(userId);
            int orderId = orderService.CreateOrder(basket.Id, Address, PaymentMethod);
            if (PaymentMethod == PaymentMethod.OnlinePaymnt)
            {
                //ثبت پرداخت
                var payment = paymentService.PayForOrder(orderId);
                //ارسال به درگاه پرداخت
                return RedirectToAction("Index", "Pay", new { PaymentId = payment.PaymentId });
                
            }
            else
            {
                //برو به صفحه سفارشات من
                return RedirectToAction("Index", "Orders", new { area = "customers" });
            }
        }

        public IActionResult Checkout()
        {
            return View();
        }


        [AllowAnonymous]
        [HttpPost]
        public IActionResult ApplyDiscount(string CouponCode, int BasketId)
        {
            var user = userManager.GetUserAsync(User).Result;
            var valisDiscount = discountService.IsDiscountValid(CouponCode, user);


            if (valisDiscount.IsSuccess)
            {
                discountService.ApplyDiscountInBasket(CouponCode, BasketId);
            }
            else
            {
                TempData["InvalidMessage"] = String.Join(Environment.NewLine, valisDiscount.Message.Select(a => String.Join(", ", a)));

            }

            return RedirectToAction(nameof(Index));
        }


        [AllowAnonymous]
        public IActionResult RemoveDiscount(int id)
        {
            discountService.RemoveDiscountFromBasket(id);
            return RedirectToAction(nameof(Index));
        }

        private BasketDto GetOrSetBasket()
        {
            if (signInManager.IsSignedIn(User))
            {
                //userId = ClaimUtility.GetUserId(User);
                return basketService.GetOrCreateBasketForUser(userId);
            }
            else
            {
                SetCookiesForBasket();
                return basketService.GetOrCreateBasketForUser(userId);
            }
        }

        private void SetCookiesForBasket()
        {
            string basketCookieName = "BasketId";
            if (Request.Cookies.ContainsKey(basketCookieName))
            {
                userId = Request.Cookies[basketCookieName];
            }
            if (userId != null) return;
            userId = Guid.NewGuid().ToString();
            var cookieOptions = new CookieOptions { IsEssential = true };
            cookieOptions.Expires = DateTime.Today.AddYears(2);
            Response.Cookies.Append(basketCookieName, userId, cookieOptions);

        }


    }
}

WebSite.EndPoint/Views/Shared/Components/BasketComponent/BasketComponent.cshtml
@using Application.BasketsService;
@model BasketDto;
@{
    Layout = null;
}

<div class="user-item cart-list">
    <a href="#">
        <i class="fal fa-shopping-basket"></i>

        @if (Model != null)
        {
            <span class="bag-items-number">@Model.Items.Count</span>
        }
        else
        {
            <span class="bag-items-number">0</span>
        }

    </a>
    <ul>
        <li class="cart-items">
            <ul class="do-nice-scroll">
                @if (Model != null)
                    foreach (var item in Model.Items)
                    {
                        <li class="cart-item">
                            <span class="d-flex align-items-center mb-2">
                                <a href="#">
                                    <img src="@item.ImageUrl" alt="">
                                </a>
                                <span>
                                    <a href="#">
                                        <span class="title-item">
                                            @item.CatalogName
                                        </span>
                                    </a>
                                    <span class="color d-flex align-items-center">
                                        تعداد:
                                        <span>@item.Quantity</span>
                                    </span>
                                </span>
                            </span>
                            <span class="price"> @item.UnitPrice.ToString("n0") تومان</span>
                            <form asp-action="RemoveItemFromBasket" asp-controller="Basket" method="post">
                                <input type="hidden" name="ItemId" value="@item.Id" />
                                <button class="remove-item">
                                    <i class="far fa-trash-alt"></i>
                                </button>

                            </form>
                        </li>
                    }
            </ul>
        </li>
        <li class="cart-footer">
            <span class="d-block text-center mb-3">
                @if (Model != null)
                {
                    <p>
                        مبلغ کل:
                        <span class="total">@Model.Total().ToString("n0")</span>
                    </p>
                }

            </span>
            <span class="d-block text-center px-2">
                <a href="~/basket" class="btn-cart">
                    مشاهده سبد خرید
                    <i class="mi mi-ShoppingCart"></i>
                </a>
            </span>
        </li>
    </ul>
</div>